services:
  backend-service:
    container_name: food-app-delivery-service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9990:9990"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      DATABASE_HOST: mysql
      DATABASE_PORT: 3306
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: root
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      CLOUDINARY_CLOUD_NAME: ${CLOUDINARY_CLOUD_NAME}
      CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY}
      CLOUDINARY_API_SECRET: ${CLOUDINARY_API_SECRET}
      MAIL_HOST: ${MAIL_HOST:-smtp.gmail.com}
      MAIL_PORT: ${MAIL_PORT:-587}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}

    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - default

  mysql:
    image: mysql:8.0
    container_name: mysql-food-app
    restart: always
    environment:
      MYSQL_DATABASE: food_app_db
      MYSQL_ROOT_PASSWORD: root
      LANG: C.UTF-8
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./initdb.sql:/docker-entrypoint-initdb.d/init.sql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    networks:
      - default
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 3

  redis:
    image: redis:7.4
    container_name: redis-food-app
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - default
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

networks:
  default:
    name: food-App-backend-service

volumes:
  mysql-data:
  redis-data: