services:
  food-app-service:
    container_name: food-app-container
    build:
      context: .  # Thư mục chứa Dockerfile
      dockerfile: Dockerfile  # Tên file Dockerfile (nếu khác thì sửa lại)
    image: food-app-image
    ports:
      - "9990:9990"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/food_app
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=password
    networks:
      - food-app-network
    depends_on:
      - db

  db:
    image: mysql:8.4.4
    container_name: mysql-container
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=food_app
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - food-app-network

networks:
  food-app-network:
    driver: bridge

volumes:
  mysql-data: