version: "3.9"

services:
    food-app-service:
        container_name: food-app-container
        image: food-app-image
        ports:
          - "9990:9990"
        networks:
          - food-app-network

networks:
    food-app-network:
        driver: bridge