server:
  port: 9991

spring:
  config:
    activate:
      on-profile: test
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      port: ${SPRING_DATA_REDIS_PORT:6379}
      host: ${SPRING_DATA_REDIS_HOST:localhost}
openapi:
  service:
    api-docs: foodApp-service
    server: http://localhost:9991
    title: Food App Service
    version: 1.0.0
