server:
  port: 9990

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://${DATABASE_HOST:localhost}:${DATABASE_PORT:3307}/food_app_db
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  data:
    redis:
      port: ${SPRING_DATA_REDIS_PORT:6379}
      host: ${SPRING_DATA_REDIS_HOST:localhost}
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: 587
    username: phamchien9254@gmail.com
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

openapi:
  service:
    api-docs: food-app
    server: http://localhost:9990
    title: Food app service
    version: 1.0.0

jwt:
  accessToken:
    secretKey: ${JWT_ACCESS_TOKEN_SECRET_KEY:bNg5ITJ8MjZGOlrQPLTOikaJI1WZqnhwrI3eypbGjyQ=}
    expiry: 3600000  # 1h
  refreshToken:
    secretKey: ${JWT_REFRESH_TOKEN_SECRET_KEY:9k1jJAWAKQCnCEz1pwcPNegbHoLugf9hgEnn6sz5pFc=}
    expiry: 1209600000  # 14d
  verificationToken:
    secretKey: ${JWT_VERIFICATION_TOKEN_SECRET_KEY:s+E3RRAIKn1Kcb5iWDsKtcV7r6g0omm7wHgdVkIyGtgA}
    expiry: 1800000  # 30m
  resetToken:
    secretKey: ${JWT_RESET_TOKEN_SECRET_KEY:FsWyO8iaNYbbs0sPDeSjWpJtL45yVIkmFIcnqC2VUmmB}
    expiry: 3600000  # 1h

cloudinary:
  cloud_name: ${CLOUDINARY_CLOUD_NAME}
  api_key: ${CLOUDINARY_API_KEY}
  api_secret: ${CLOUDINARY_API_SECRET}