server:
  port: 9990

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://localhost:3307/food_app
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      initialization-fail-timeout: 60000
      connection-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform:
      org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        format_sql: true
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: 587
    username: phamchien9254@gmail.com
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

openapi:
  service:
    api-docs: food-app
    server: http://localhost:9990
    title: Food app service
    version: 1.0.0

jwt:
  expiryHour: 1
  expiryDay: 14
  accessKey: bNg5ITJ8MjZGOlrQPLTOikaJI1WZqnhwrI3eypbGjyQ=
  refreshKey: 9k1jJAWAKQCnCEz1pwcPNegbHoLugf9hgEnn6sz5pFc=
  verificationKey: s+E3RRAIKn1Kcb5iWDsKtcV7r6g0omm7wHgdVkIyGtgA
  resetKey: FsWyO8iaNYbbs0sPDeSjWpJtL45yVIkmFIcnqC2VUmmB

otp:
  verification:
    expiryMinute: 5
  reset-password:
    expiryMinute: 5
  update-email:
    expiryMinute: 10
  update-phone:
    expiryMinute: 10

cloudinary:
  cloud_name: ${CLOUDINARY_CLOUD_NAME}
  api_key: ${CLOUDINARY_API_KEY}
  api_secret: ${CLOUDINARY_API_SECRET}